y2s/y2s/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.static import serve
from django.conf.urls import url
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('y2s_downloader.urls')),


    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

y2s/y2s_downloader/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'ytproject'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , views.y2s_down),
    path('download/',views.y2s_download),
    path('download/<resolution>/',views.yt_doanload_done,name='download_done')


]

y2s/y2s_downloader/models.py
from django.db import models

# Create your models here.

y2s/y2s_downloader/views.py
from django.shortcuts import render
# pytube
from pytube import YouTube
import os


# Create your views here.

def y2s_down(request):
    return render(request, 'y2s main.html')


def y2s_download(request):
    global url
    url = request.GET.get('link')
    video = YouTube(url)


    video_stream = video.streams.filter(progressive=True).all()
    embd_link = url.replace('watch?v=', 'embed/')

    titles = video.title

    context = {'video': video_stream, "embed": embd_link, "titled": titles}



    return render(request, 'y2s download.html', context)


def yt_doanload_done(request,resolution) :
    global url
    homedir = os.path.expanduser("~")
    dirs = homedir + '/Downloads'
    if request.method =="POST" :
        YouTube(url).streams.get_by_resolution(resolution).download(dirs)
        return render(request,'done.html')
    else :
        return render(request , 'error.html')

y2s/y2s_downloader/templates/done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>y2s-->successfull</title>
</head>
<body>
<center> <h3>The process of downloadinbg your video is started</h3>
    <p> for more download please visit this website and also share with your friend</p>
</center>

</body>
</html>

y2s/y2s_downloader/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>error</title>
</head>
<body>
some things went wrong

</body>
</html>

y2s/y2s_downloader/templates/y2s download.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet" />
    <title>Hello, world!</title>
  </head>
  <body>

  <center>
    <h1>Your video shown here :)</h1>
    <div class="sizer" style="width: 300px;">
  <div class="embed-responsive embed-responsive-16by9">
   <iframe class="embed-responsive-item" src="{{embed}}" allowfullscreen></iframe>
  </div>
</div>
  </center>
<!--  title-->
  <center>
    <h3>Title: </h3>
    <h6>{{titled}}</h6>
  </center>

<!--title-->
<!--  table-->
<table class="table table-borderless">
  <thead class="bg-dark  " style="color:white">
    <tr>


      <th scope="col">Resolution</th>
      <th scope="col">Size</th>
      <th scope="col">Download</th>
    </tr>
  </thead>
  <tbody>
  {% for i in video %}
    <tr>

      <td>{{i.resolution}}</td>
      <td>{{i.filesize}} kb</td>
      <td><form action="{%url 'ytproject:download_done' i.resolution %}" , method="post">
        {% csrf_token %}
        <input type="submit" class = "btn btn-success" value = " Download">
      </form></td>
    </tr>
  {% endfor %}

  </tbody>
</table>
<!--  table-->







    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

y2s/y2s_downloader/templates/y2s main.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>y2s-->downloader</title>
  </head>
  <body>


<!--  navbar start from here-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <a class="navbar-brand" href="#">Y2S-->Downloader</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">youtube video<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">instagram video</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">facebook video</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Feedback</a>
      </li>
    </ul>
  </div>
</nav>
<!--navbar end here-->
<br>
<br>


<div class="cointainer">
    <center>

        <h1>Enter your youtube video link here</h1>
        <br>
        <br>


        <!--    form start here-->
    <form action="download/" , method="get">
  <div class="form-group">
    <label for="exampleInputEmail1">Enter url here</label>
      <br>
    <input name = "link" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="www.youtube.com">
    <small id="emailHelp" class="form-text text-muted">As this website is add free . so please share it with your friend</small>
  </div>

<br>
        <br>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
<!--    form end here-->
    </center>



</div>




















    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>